### ISSUE TITLE
Add Support for .Net Standard and Framework

### ISSUE THREAD

**Issue by RCP161** [WildGums/Orc.EntityFrameworkCore#171]
## Summary
Please add Support for .Net Standard and Framework. I know it's in an alpha release, but there are 1,3 k downloads and there are as far as I know, no dependencies wich block. Sorry if I am wrong, I am new at .net Standard and Core.

## API Changes
There should be none. Maybe some UnitTest have to be written.

## Intended Use Case
Using Ef Core and Orc.EntityFrameworkCore in a .Net Standard library.

**Comment by GeertvanHorrik** [comment]
We will consider, but what are the benefits of targeting .NET Framework? Especially for *new* packages, it feels a bit useless. We might consider .net standard, but for us we are only targeting .NET Core since this year.

**Comment by RCP161** [comment]
Yea, .Net Standard would be enught. We have checked, if oure WPF application can be  ported to Core 3.0, but we have an external library, wich isn't available yet. So at the moment we couldn't port it and we don't know, how long it will take, untill a .Net Standard or Core version for production will be available.

**Comment by GeertvanHorrik** [comment]
Have you tried referencing it from .net core? I believe .net core can load full .net libraries in most cases as long as it doesn't use some features that are no longer supported in .net core.

**Comment by RCP161** [comment]
Thanks for that tipp. I will check this. 
However, support from .Net Standard would maybe be helpful in some cases. I don't know, if this would result in more work. I have only tried to set the NetStandard flag in the project in this source code, but it has not compiled. So I don't know what is missing.

**Comment by GeertvanHorrik** [comment]
With .net 5 being released, we will only target .netcoreapp3.1 and net5.0 for our libraries moving forward. This will greatly decrease build / develop time and it's what we use ourselves in the future as well.
